const Strings = {
  welcome: 'Welcome',
  welcomeScreenSubText1: 'Have a better helping experience',
  createAccount: 'Create an account',
  Log_in: 'Log In',
  Sign_in: 'Sign In',
  Login: 'Login',
  Sign_up: 'Sign Up',
  cancel: 'Cancel',
  register: 'Register',
  Back: 'Back',
  profile: 'Profile',
  name: 'Name',
  full_name: 'Full Name',
  street: 'Street',
  City: 'City',
  save: 'Save',
  Postal_code: 'Postal Code',
  and: 'And',
  email: 'Email',
  SignIn_Heading: 'Sign in with your email or phone number',
  SignUp_Heading: 'Sign up with your email or phone number',
  email_phone: 'Email or Phone Number',
  enter_pwd: 'Enter Your Password',
  conf_pwd: 'Confirm Password',
  your_number: 'Your mobile number',
  forgotpwd: 'Forget password?',
  or: 'or',
  ok: 'OK',
  login_google: 'Login with Google',
  login_facebook: 'Login with Facebook',
  login_apple: 'Login with Apple',
  singup_google: 'Sign Up with Google',
  singup_facebook: 'Sign Up with Facebook',
  singup_apple: 'Sign Up with Apple',
  have_Account: 'Already have an account?',
  dont_account: 'Don’t have an account?',
  dont_get_otp: 'Didn’t receive code? ',
  gender: 'Gender',
  set_pwd: 'Set password',
  set_ur_pwd: 'Set your password',
  pwd_sub: 'Atleast 1 number or a special character',
  resend: 'Resend',
  verify: 'Verify',
  message: 'Message',
  code_Sent: 'OTP sent again',
  verification_sub: 'Enter your OTP code',
  phone_verification: 'Phone verification',
  term_start_Text: 'By signing up. you agree to the ',
  tos: 'Terms of service',
  tos_content:
    '<div><p><strong>HandyHelp Terms and Conditions</strong></p><p><strong>1. Refund and Cancellation Policy</strong></p><p>Details of our refund and cancellation policy can be found within the app. Users can refer to this policy for information on refunds and cancellations.</p><p><strong>2. Privacy and Data Security</strong></p><p>We take user privacy and data security seriously. Your data will be fully protected and safe. Our data handling practices are outlined in our <a href="#privacy-policy">Privacy Policy</a>. If you have concerns about data security, you can contact our support team for assistance.</p><p><strong>3. Customer Support Channels</strong></p><p>We provide customer support through multiple channels, including:</p><ul><li>In-app chat support</li><li>Email support (<a href="mailto:support@HandyHelp.com" target="_blank">support@HandyHelp.com</a>)</li><li>Phone support (optional)</li><li>FAQ and knowledge base on our website</li></ul><p><strong>4. Response Time for Inquiries</strong></p><p>We strive to respond to customer inquiries within 24 hours during business hours. Our standard business hours for customer support are 9:00 AM to 6:00 PM, Monday to Friday, EST. Emergency support may be available outside these hours. We aim to resolve customer issues as quickly as possible, and resolution times may vary depending on the issue`s complexity. We will provide regular updates on the status of ongoing problems.</p><p><strong>5. Disclaimer</strong></p><p>We are not responsible for the work or payment between users. HandyHelp provides a platform for connecting people in need with those offering services. The terms of work, payment, and any disputes are solely between the parties involved. HandyHelp is not a party to any agreements or transactions between users.</p><p><strong>6. User Responsibilities</strong></p><p>Users are responsible for their conduct and interactions on the HandyHelp platform. This includes abiding by all applicable laws and regulations, treating others with respect, and fulfilling any agreements made with other users. Users must not engage in any unlawful, harmful, or disruptive activities on the platform.</p><p><strong>7. Account Security</strong></p><p>Users are responsible for maintaining the security of their accounts and credentials. They must not share their login information with others and should notify HandyHelp immediately if they suspect unauthorized access to their account.</p><p><strong>8. Content and Reviews</strong></p><p>Users may create and share content on the HandyHelp platform, including reviews and ratings. Content must be accurate, respectful, and compliant with our guidelines. HandyHelp reserves the right to remove or moderate content that violates our policies.</p><p><strong>9. Termination of Accounts</strong></p><p>HandyHelp may suspend or terminate user accounts for violations of our terms and conditions. Users must comply with all applicable policies and guidelines to maintain their account in good standing.</p><p><strong>10. Changes to Terms and Conditions</strong></p><p>HandyHelp reserves the right to update these terms and conditions as needed. Users will be notified of any changes, and it is their responsibility to review and accept the updated terms to continue using the platform.</p><p><strong>11. Governing Law</strong></p><p>These terms and conditions are governed by the laws of [insert governing jurisdiction]. Any disputes or legal actions will be subject to the jurisdiction of the courts in [insert jurisdiction].</p></div>',
  pri_policy: 'Privacy policy',
  pri_policy_content:
    '<div ><p >1. Refund and Cancellation Policy: Details of our refund and cancellation policy can be found within the app. Users can refer to this policy for information on refunds and cancellations.</p><p >2. Privacy and Data Security: We take user privacy and data security seriously. Their data will be fully protected and safe. Our data handling practices are outlined in our Privacy Policy. If users have concerns about data security, they can contact our support team for assistance.</p><p >3. Customer Support Channels: We provide customer support through multiple channels, including:</p><ul ><li >In-app chat support</li><li >Email support (<a  href="mailto:support@HandyHelp.com" target="_blank"><span class="supporthandyhelpcom1">support@HandyHelp.com</span></a>)</li><li >Phone support (optional)</li><li >FAQ and knowledge base on our website</li></ul><p >4. Response Time for Inquire: We strive to respond to customer inquiries within [insert response time, e.g., 24 hours] during business hours. Our standard business hours for customer support are [insert hours of operation, e.g., 9:00 AM to 6:00 PM, Monday to Friday, EST]. Emergency support may be available outside these hours. We aim to resolve customer issues as quickly as possible, and resolution times may vary depending on the issue`s complexity. We will provide regular updates on the status of the ongoing problems.</p><p >5. We are not responsible for your work or pay. We are providing service and conneting people are in need.</p></div>',
};

export default Strings;
